# -- coding utf-8 --
Final_Project.ipynb

Automatically generated by Colab.

Original file is located at
    httpscolab.research.google.comdrive1f4synY85Wcp6_2Nl7AZ0t3zNSih65cqw


# XAI-Powered Phishing URL Detection System
# Enterprise-Grade Data Preprocessing Pipeline
# Dataset PhiUSIIL_Phishing_URL_Dataset.csv
# Target Models LR, KNN, SVM, ANN, RF, XGBoost

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import SMOTE
import warnings
warnings.filterwarnings(ignore)


print(=  60)
print(STEP 1 Data Loading & Initial Cleanup)
print(=  60)

# Load the raw dataset from disk
df = pd.read_csv(contentPhiUSIIL_Phishing_URL_Dataset.csv)
print(f[INFO] Raw dataset loaded — Shape {df.shape})

# --- Drop strictly text-based and non-predictive columns ---
# These columns carry no generalizable signal for ML models
#   FILENAME  internal file reference, not a URL feature
#   URL       raw string — processed features already extracted from it
#   Domain    raw string — DomainLength, IsDomainIP, etc. encode its info
#   TLD       raw string — TLDLength and TLDLegitimateProb encode its info
#   Title     raw HTML title text — DomainTitleMatchScore encodes its signal
cols_to_drop = [FILENAME, URL, Domain, TLD, Title]

# Drop gracefully only remove a column if it actually exists in the dataset
# This makes the pipeline robust to different dataset versions
existing_to_drop = [col for col in cols_to_drop if col in df.columns]
df.drop(columns=existing_to_drop, inplace=True)
print(f[INFO] Dropped textnon-predictive columns {existing_to_drop})
print(f[INFO] Dataset shape after dropping {df.shape})

# --- Fill any remaining missing values with 0 ---
# Using 0 is semantically safe here (e.g., missing count = 0 occurrences)
# and prevents errors in scaling and model training
missing_before = df.isnull().sum().sum()
df.fillna(0, inplace=True)
missing_after = df.isnull().sum().sum()
print(f[INFO] Missing values filled — Before {missing_before}, After {missing_after})


print(n + =  60)
print(STEP 2 Feature & Target Separation)
print(=  60)

# Separate the binary target label (1 = Safe, 0 = Phishing)
y = df[label]
X = df.drop(columns=[label])
print(f[INFO] Target (y) shape {y.shape})
print(f[INFO] Features (X) shape before encoding {X.shape})
print(f[INFO] Class distribution — Safe (1) {(y == 1).sum()}, Phishing (0) {(y == 0).sum()})

# --- Apply One-Hot Encoding for any remaining categoricaltext columns ---
# drop_first=True removes one dummy variable per category to avoid the
# dummy variable trap (perfect multicollinearity), which is especially
# important for Logistic Regression and SVM
categorical_cols = X.select_dtypes(include=[object, category]).columns.tolist()
if categorical_cols
    print(f[INFO] Applying One-Hot Encoding on {categorical_cols})
    X = pd.get_dummies(X, columns=categorical_cols, drop_first=True)
    print(f[INFO] Features (X) shape after encoding {X.shape})
else
    print([INFO] No remaining categorical columns found — skipping OHE.)

# Ensure all feature columns are numeric (safety guard)
X = X.astype(float)


print(n + =  60)
print(STEP 3 Feature Selection (Remove Multicollinearity))
print(=  60)

# Compute the absolute Pearson correlation matrix between all features
# We use absolute values because both strong positive (+0.95) and
# strong negative (−0.95) correlations indicate redundant information
corr_matrix = X.corr().abs()

# Extract the upper triangle of the matrix to avoid checking each pair twice
# (e.g., we don't need both corr(A,B) and corr(B,A))
upper_triangle = corr_matrix.where(
    np.triu(np.ones(corr_matrix.shape), k=1).astype(bool)
)

# Identify columns that are highly correlated ( 0.90) with at least one
# other column. The k=1 offset above ensures a feature is never compared
# against itself (diagonal is excluded).
CORRELATION_THRESHOLD = 0.90
cols_to_remove = [
    col for col in upper_triangle.columns
    if any(upper_triangle[col]  CORRELATION_THRESHOLD)
]

print(f[INFO] Correlation threshold {CORRELATION_THRESHOLD})
print(f[INFO] Highly correlated features to drop ({len(cols_to_remove)}) {cols_to_remove})

X.drop(columns=cols_to_remove, inplace=True)
print(f[INFO] Features (X) shape after multicollinearity removal {X.shape})


print(n + =  60)
print(STEP 4 Stratified Train-Test Split)
print(=  60)

# stratify=y ensures the ratio of SafePhishing URLs is preserved in BOTH
# the training and testing sets — critical for fair model evaluation
# random_state=42 guarantees reproducibility across runs
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print(f[INFO] X_train shape {X_train.shape})
print(f[INFO] X_test  shape {X_test.shape})
print(f[INFO] y_train distribution — Safe {(y_train == 1).sum()}, Phishing {(y_train == 0).sum()})
print(f[INFO] y_test  distribution — Safe {(y_test  == 1).sum()}, Phishing {(y_test  == 0).sum()})


print(n + =  60)
print(STEP 5 Feature Scaling (StandardScaler))
print(=  60)

# StandardScaler transforms each feature to have mean=0 and std=1.
# This is MANDATORY for distance-based models (KNN, SVM) and gradient-based
# models (LR, ANN) to prevent features with large numeric ranges from
# dominating those with small ranges.

#  CRITICAL DATA LEAKAGE RULE 
# We call .fit_transform() ONLY on X_train so the scaler learns
# the mean and std from training data exclusively.
# We then call .transform() (no fit) on X_test — the test set is scaled
# using training statistics, exactly as it would be in production.
# Fitting on X_test or the full dataset before splitting would leak
# test-set distribution information into training, inflating accuracy.

scaler = StandardScaler()

# Fit on training data and transform it
X_train_scaled_arr = scaler.fit_transform(X_train)

# Transform test data using the SAME scaler (fitted on train only)
X_test_scaled_arr  = scaler.transform(X_test)

# Convert numpy arrays back to DataFrames so XAI tools (SHAP, LIME) can
# access feature names directly — essential for explainability reports
X_train_scaled = pd.DataFrame(X_train_scaled_arr, columns=X_train.columns, index=X_train.index)
X_test_scaled  = pd.DataFrame(X_test_scaled_arr,  columns=X_test.columns,  index=X_test.index)

print(f[INFO] Scaler fitted on X_train only (no data leakage).)
print(f[INFO] X_train_scaled shape (before SMOTE) {X_train_scaled.shape})
print(f[INFO] X_test_scaled  shape                 {X_test_scaled.shape})


print(n + =  60)
print(STEP 6 Handle Class Imbalance (SMOTE))
print(=  60)

# Class imbalance before SMOTE
print(f[INFO] Class distribution BEFORE SMOTE)
print(f       Safe (1) {(y_train == 1).sum()}, Phishing (0) {(y_train == 0).sum()})

# SMOTE (Synthetic Minority Over-sampling Technique) generates synthetic
# samples for the minority class (Phishing = 0) by interpolating between
# existing minority-class instances using K-Nearest Neighbors.
#
#  WHY TRAIN-ONLY 
# Applying SMOTE to test data would create artificial samples in evaluation,
# making performance metrics unreliable and misleading. The test set must
# remain 100% real, unseen data to reflect true deployment performance.
#
# random_state=42 ensures the synthetic samples are reproducible.
smote = SMOTE(random_state=42)
X_train_scaled, y_train = smote.fit_resample(X_train_scaled, y_train)

# Convert the resampled output back to a DataFrame with original column names
# (SMOTE returns a numpy array; DataFrame is needed for XAI downstream)
X_train_scaled = pd.DataFrame(X_train_scaled, columns=X.columns)

print(f[INFO] Class distribution AFTER SMOTE)
print(f       Safe (1) {(y_train == 1).sum()}, Phishing (0) {(y_train == 0).sum()})


print(n + =  60)
print(PIPELINE COMPLETE — Final Output Shapes)
print(=  60)
print(f[RESULT] X_train_scaled (after SMOTE)  {X_train_scaled.shape})
print(f[RESULT] y_train        (after SMOTE)  {y_train.shape})
print(f[RESULT] X_test_scaled  (original)     {X_test_scaled.shape})
print(f[RESULT] y_test         (original)     {y_test.shape})
print(=  60)
print([INFO] Artifacts ready for downstream models LR, KNN, SVM, ANN, RF, XGBoost)
print([INFO] Feature names preserved in DataFrames for SHAPLIME XAI compatibility.)
print(=  60)

# XAI-Powered Phishing URL Detection System
# Assumes preprocessing variables are already in the environment.
# Run after phishing_preprocessing_pipeline.py

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.ticker as mticker
import seaborn as sns
import warnings
warnings.filterwarnings(ignore)

# A consistent dark-theme palette used across all 5 graphs for
# a polished, presentation-ready look.

plt.rcParams.update({
    figure.facecolor  #0F1117,
    axes.facecolor    #181C27,
    axes.edgecolor    #2E3350,
    axes.labelcolor   #C8D0E7,
    axes.titlecolor   #FFFFFF,
    axes.titlesize    15,
    axes.labelsize    12,
    axes.titleweight  bold,
    axes.grid         True,
    grid.color        #2E3350,
    grid.linestyle    --,
    grid.alpha        0.5,
    xtick.color       #8892B0,
    ytick.color       #8892B0,
    xtick.labelsize   10,
    ytick.labelsize   10,
    text.color        #C8D0E7,
    legend.facecolor  #1E2235,
    legend.edgecolor  #2E3350,
    legend.fontsize   10,
    font.family       DejaVu Sans,
})

CLR_SAFE     = #00E5B0   # Teal-green  - Safe  legitimate URLs
CLR_PHISHING = #FF4B6E   # Coral-red   - Phishing URLs
CLR_BEFORE   = #FFB347   # Amber       - Before states
CLR_AFTER    = #00E5B0   # Teal        - After states

LABEL_MAP   = {0 Phishing, 1 Safe}
PALETTE_MAP = {Safe CLR_SAFE, Phishing CLR_PHISHING}


def add_footer(fig, text=PhiUSIIL Phishing URL Detection    Preprocessing Pipeline)
    fig.text(0.99, 0.01, text,
             ha=right, va=bottom,
             fontsize=8, color=#3D4566, style=italic)


print(=  65)
print(Generating Graph 1 Class Distribution Before and After SMOTE (Bar Chart)...)
print(=  65)

before_counts = y_train.value_counts().sort_index()
after_counts  = pd.Series(y_train).value_counts().sort_index()

classes    = [Phishing (0), Safe (1)]
before_val = [before_counts.get(0, 0), before_counts.get(1, 0)]
after_val  = [after_counts.get(0, 0),  after_counts.get(1, 0)]

x     = np.arange(len(classes))
width = 0.34

fig, ax = plt.subplots(figsize=(10, 6))
fig.patch.set_facecolor(#0F1117)

bars_before = ax.bar(x - width  2, before_val, width,
                     color=CLR_BEFORE, alpha=0.88,
                     label=Before SMOTE, zorder=3,
                     edgecolor=#0F1117, linewidth=1.2)
bars_after  = ax.bar(x + width  2, after_val, width,
                     color=CLR_AFTER,  alpha=0.88,
                     label=After SMOTE,  zorder=3,
                     edgecolor=#0F1117, linewidth=1.2)

for bar in bars_before
    ax.text(bar.get_x() + bar.get_width()  2,
            bar.get_height() + 800,
            f{bar.get_height(),.0f},
            ha=center, va=bottom,
            fontsize=9.5, color=CLR_BEFORE, fontweight=bold)

for bar in bars_after
    ax.text(bar.get_x() + bar.get_width()  2,
            bar.get_height() + 800,
            f{bar.get_height(),.0f},
            ha=center, va=bottom,
            fontsize=9.5, color=CLR_AFTER, fontweight=bold)

ratio = before_val[1]  max(before_val[0], 1)
ax.annotate(
    fOriginal ratio  {ratio.2f}  1  (Safe  Phishing)n
    fSMOTE synthetically corrects this to  1  1,
    xy=(0.5, 0.91), xycoords=axes fraction, ha=center,
    fontsize=10, color=#8892B0,
    bbox=dict(boxstyle=round,pad=0.45, fc=#1E2235,
              ec=#2E3350, alpha=0.85)
)

ax.set_xticks(x)
ax.set_xticklabels(classes, fontsize=11)
ax.yaxis.set_major_formatter(
    mticker.FuncFormatter(lambda v, _ f{int(v),})
)
ax.set_title(Class Distribution  ·  Before vs. After SMOTE, fontsize=16, pad=18)
ax.set_ylabel(Sample Count)
ax.set_xlabel(Target Class)
ax.legend(loc=upper left, framealpha=0.9)
ax.set_ylim(0, max(after_val)  1.20)
ax.spines[[top, right]].set_visible(False)

add_footer(fig)
plt.tight_layout()
plt.show()


print(n + =  65)
print(Generating Graph 2 Feature Distribution Before and After Scaling (HistogramKDE)...)
print(=  65)

# LargestLineLength spans 22 to ~14 million in raw form — a perfect subject
# for demonstrating how StandardScaler compresses extreme ranges.
FEATURE = LargestLineLength

# Clip at 99th percentile to suppress extreme outliers that squash the histogram
p99      = X_train[FEATURE].quantile(0.99)
raw_data = X_train[FEATURE].clip(upper=p99)

scaled_data = X_train_scaled[FEATURE]

fig, axes = plt.subplots(1, 2, figsize=(14, 6))
fig.patch.set_facecolor(#0F1117)
fig.suptitle(
    fFeature Distribution  Before & After StandardScalern'{FEATURE}',
    fontsize=15, fontweight=bold, color=white, y=1.01
)

ax0 = axes[0]
ax0.set_facecolor(#181C27)
sns.histplot(raw_data, bins=60, ax=ax0,
             color=CLR_BEFORE, alpha=0.70)
sns.kdeplot(raw_data, ax=ax0, color=#FFDD99, linewidth=2.5,
            bw_adjust=1.5)
ax0.set_title(Before Scaling  (Raw Values), fontsize=13)
ax0.set_xlabel(f{FEATURE}  —  raw value (clipped @ 99th pct))
ax0.set_ylabel(Frequency)
ax0.xaxis.set_major_formatter(
    mticker.FuncFormatter(lambda v, _ f{v,.0f})
)
ax0.tick_params(axis=x, rotation=30)

mu_raw = raw_data.mean()
ax0.axvline(mu_raw, color=#FFD700, linestyle=--, linewidth=1.5)
ax0.text(mu_raw  1.03, ax0.get_ylim()[1]  0.90,
         fμ = {mu_raw,.0f}, color=#FFD700, fontsize=9)

ax1 = axes[1]
ax1.set_facecolor(#181C27)
sns.histplot(scaled_data, bins=60, ax=ax1,
             color=CLR_AFTER, alpha=0.70)
sns.kdeplot(scaled_data, ax=ax1, color=#99FFE3, linewidth=2.5,
            bw_adjust=1.5)
ax1.set_title(After Scaling  (μ = 0, σ = 1), fontsize=13)
ax1.set_xlabel(f{FEATURE}  —  standardised z-score)
ax1.set_ylabel()

mu_sc = scaled_data.mean()
ax1.axvline(mu_sc, color=#FFD700, linestyle=--, linewidth=1.5)
ax1.text(mu_sc + 0.05, ax1.get_ylim()[1]  0.90,
         fμ ≈ {mu_sc.3f}, color=#FFD700, fontsize=9)

ax1.axvspan(-1, 1, alpha=0.08, color=CLR_AFTER)
ax1.text(0, ax1.get_ylim()[1]  0.78,
         68% withinn±1 σ,
         ha=center, fontsize=8.5, color=#8892B0)

for ax in axes
    ax.spines[[top, right]].set_visible(False)

add_footer(fig)
plt.tight_layout()
plt.show()


print(n + =  65)
print(Generating Graph 3 Correlation Heatmap for Top Features...)
print(=  65)

# Join the label back onto scaled features to find the top discriminators
heatmap_df          = X_train_scaled.copy()
heatmap_df[label] = y_train.values

# Select top 15 features by absolute Pearson correlation with the target
corr_with_label = (
    heatmap_df.corr()[label]
    .abs()
    .sort_values(ascending=False)
)
top15_cols = corr_with_label.drop(label).head(15).index.tolist()

# Build correlation sub-matrix for those 15 features + label
sub_corr = heatmap_df[top15_cols + [label]].corr()

# Diverging palette deep-red - white - deep-teal
cmap = sns.diverging_palette(355, 170, s=90, l=40, as_cmap=True)

fig, ax = plt.subplots(figsize=(14, 11))
fig.patch.set_facecolor(#0F1117)
ax.set_facecolor(#0F1117)

hm = sns.heatmap(
    sub_corr, ax=ax,
    cmap=cmap, center=0,
    annot=True, fmt=.2f,
    annot_kws={size 8.5, weight bold},
    linewidths=0.6, linecolor=#0F1117,
    square=True,
    cbar_kws={shrink 0.72, label Pearson r}
)

hm.collections[0].colorbar.ax.yaxis.label.set_color(white)
hm.collections[0].colorbar.ax.tick_params(colors=#8892B0, labelsize=8)

ax.set_title(
    Feature Correlation Matrix  ·  Top 15 Features + Target Labeln
    (Scaled training data    Pearson r),
    fontsize=14, pad=18
)
ax.tick_params(axis=x, rotation=45, labelsize=9)
ax.tick_params(axis=y, rotation=0,  labelsize=9)

add_footer(fig)
plt.tight_layout()
plt.show()

# VISUAL STEP 4 — Feature Separation & Outliers (Box Plot + Violin overlay)

print(n + =  65)
print(Generating Graph 4 Feature Separation & Outliers (Box Plot)...)
print(=  65)

# Top-3 continuous discriminators from the correlation analysis above.
# These show the clearest median separation between Safe and Phishing.
BOX_FEATURES = [URLSimilarityIndex, CharContinuationRate, URLCharProb]

# Build a tidy long-form DataFrame for seaborn
plot_df          = X_train_scaled[BOX_FEATURES].copy()
plot_df[Class] = y_train.map(LABEL_MAP).values

long_df = plot_df.melt(
    id_vars=Class,
    value_vars=BOX_FEATURES,
    var_name=Feature,
    value_name=Scaled Value
)

fig, ax = plt.subplots(figsize=(13, 7))
fig.patch.set_facecolor(#0F1117)
ax.set_facecolor(#181C27)

# Transparent violin layer for density shape context
sns.violinplot(
    data=long_df,
    x=Feature, y=Scaled Value, hue=Class,
    palette=PALETTE_MAP,
    inner=None, alpha=0.12,
    dodge=True, linewidth=0,
    ax=ax, legend=False
)

# Solid box plot on top — clearly shows IQR, median, and outliers
sns.boxplot(
    data=long_df,
    x=Feature, y=Scaled Value, hue=Class,
    palette=PALETTE_MAP,
    width=0.50, linewidth=1.3,
    fliersize=2.5,
    flierprops=dict(marker=o, alpha=0.22, linewidth=0),
    medianprops=dict(linewidth=2.5, color=#FFFFFF),
    boxprops=dict(alpha=0.85),
    ax=ax
)

ax.set_title(
    Feature Separation Power & Outlier Profile by Classn
    (Standardised values    Violin = density  ·  Box = IQR + median),
    fontsize=14, pad=16
)
ax.set_xlabel(Feature)
ax.set_ylabel(Standardised Value (z-score))
ax.axhline(0, color=#2E3350, linewidth=1.2, linestyle=--)

# Keep only the box-plot legend entries (skip duplicate violin entries)
handles, labels = ax.get_legend_handles_labels()
ax.legend(handles[2], labels[2],
          title=Class, title_fontsize=10, framealpha=0.85)

ax.spines[[top, right]].set_visible(False)

# Annotate median delta for each feature to quantify separation
for i, feat in enumerate(BOX_FEATURES)
    sub = long_df[long_df[Feature] == feat]
    med_safe  = sub[sub[Class] == Safe][Scaled Value].median()
    med_phish = sub[sub[Class] == Phishing][Scaled Value].median()
    delta = abs(med_safe - med_phish)
    ax.text(i, ax.get_ylim()[1]  0.97,
            fΔ median = {delta.2f},
            ha=center, fontsize=9, color=#8892B0,
            bbox=dict(boxstyle=round,pad=0.25,
                      fc=#1E2235, ec=#2E3350, alpha=0.85))

add_footer(fig)
plt.tight_layout()
plt.show()


print(n + =  65)
print(Generating Graph 5 Relationship Between Two Key Features (Scatter Plot)...)
print(=  65)

# URLSimilarityIndex vs. CharContinuationRate
#   Both are top-5 discriminators and are continuous — ideal for a scatter.
#   Plotting z-scores keeps both axes on a comparable scale.
X_FEAT = URLSimilarityIndex
Y_FEAT = CharContinuationRate

scatter_df          = X_train_scaled[[X_FEAT, Y_FEAT]].copy()
scatter_df[Class] = y_train.map(LABEL_MAP).values

# Sample 6,000 points per class for visual clarity and rendering speed
sample_df = pd.concat([
    grp.sample(n=min(6000, len(grp)), random_state=42)
    for _, grp in scatter_df.groupby(Class)
]).reset_index(drop=True)

fig, ax = plt.subplots(figsize=(13, 8))
fig.patch.set_facecolor(#0F1117)
ax.set_facecolor(#181C27)

# Scatter layer — semi-transparent to reveal density
for cls, color in PALETTE_MAP.items()
    subset = sample_df[sample_df[Class] == cls]
    ax.scatter(
        subset[X_FEAT], subset[Y_FEAT],
        c=color, label=cls,
        alpha=0.28, s=14,
        edgecolors=none,
        rasterized=True    # GPU-friendly for large point counts
    )

# KDE contour overlay — shows cluster boundaries more clearly than dots alone
for cls, color in PALETTE_MAP.items()
    subset = sample_df[sample_df[Class] == cls]
    try
        sns.kdeplot(
            data=subset, x=X_FEAT, y=Y_FEAT,
            ax=ax, color=color,
            levels=4, linewidths=1.3, alpha=0.70
        )
    except Exception
        pass    # skip KDE gracefully if bandwidth estimation fails

# Reference cross-hair at the StandardScaler origin (0, 0)
ax.axhline(0, color=#2E3350, linewidth=1.0, linestyle=--, zorder=1)
ax.axvline(0, color=#2E3350, linewidth=1.0, linestyle=--, zorder=1)

ax.set_title(
    fFeature Relationship  ·  {X_FEAT}  vs.  {Y_FEAT}n
    Class separation visualised    6,000 samples per class    KDE contours overlaid,
    fontsize=13, pad=16
)
ax.set_xlabel(f{X_FEAT}  (z-score), fontsize=12)
ax.set_ylabel(f{Y_FEAT}  (z-score), fontsize=12)

# Fully opaque legend patches (dots at 0.28 alpha would be hard to read)
legend_handles = [
    mpatches.Patch(color=CLR_SAFE,     label=Safe (1)),
    mpatches.Patch(color=CLR_PHISHING, label=Phishing (0)),
]
ax.legend(handles=legend_handles,
          title=Class, title_fontsize=10,
          framealpha=0.90, loc=upper right)

ax.spines[[top, right]].set_visible(False)

# Interpretation callout
ax.annotate(
    Distinct cluster regions indicatenstrong discriminative feature power,
    xy=(0.02, 0.96), xycoords=axes fraction,
    va=top, fontsize=9.5, color=#8892B0,
    bbox=dict(boxstyle=round,pad=0.42,
              fc=#1E2235, ec=#2E3350, alpha=0.88)
)

add_footer(fig)
plt.tight_layout()
plt.show()

print(n + =  65)
print(All 5 visualizations generated successfully.)
print(Artifacts ready for presentation  XAI report inclusion.)
print(=  65)

# XAI-Powered Phishing URL Detection System
# Assumes preprocessing variables are already in the environment
#   X_train_scaled, y_train_smote  → balanced training data
#   X_test_scaled,  y_test         → original (unseen) test data

# ── Core libraries ────────────────────────────────────────────────────────────
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
import warnings
warnings.filterwarnings(ignore)

# ── Scikit-learn classifiers ──────────────────────────────────────────────────
from sklearn.linear_model    import LogisticRegression
from sklearn.neighbors       import KNeighborsClassifier
from sklearn.svm             import SVC
from sklearn.neural_network  import MLPClassifier
from sklearn.ensemble        import RandomForestClassifier

# ── XGBoost classifier ────────────────────────────────────────────────────────
from xgboost import XGBClassifier

# ── Evaluation utilities ──────────────────────────────────────────────────────
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_curve,
    auc,
    accuracy_score,
)

# Consistent dark theme across all model visualizations.

plt.rcParams.update({
    figure.facecolor  #0F1117,
    axes.facecolor    #181C27,
    axes.edgecolor    #2E3350,
    axes.labelcolor   #C8D0E7,
    axes.titlecolor   #FFFFFF,
    axes.titlesize    13,
    axes.labelsize    11,
    axes.titleweight  bold,
    axes.grid         True,
    grid.color        #2E3350,
    grid.linestyle    --,
    grid.alpha        0.45,
    xtick.color       #8892B0,
    ytick.color       #8892B0,
    xtick.labelsize   10,
    ytick.labelsize   10,
    text.color        #C8D0E7,
    legend.facecolor  #1E2235,
    legend.edgecolor  #2E3350,
    legend.fontsize   10,
    font.family       DejaVu Sans,
})

# Brand colours reused in every plot
CLR_SAFE      = #00E5B0    # teal   → Safe  True class
CLR_PHISHING  = #FF4B6E    # coral  → Phishing  False class
CLR_ROC       = #7B8CDE    # indigo → ROC curve line
CLR_DIAGONAL  = #FFB347    # amber  → random-guess diagonal
HEATMAP_CMAP  = YlOrRd     # heatmap palette (light → dark)

CLASS_NAMES   = [Phishing (0), Safe (1)]


# train_evaluate_plot()
#   Encapsulates the full sequential workflow for ONE model so the code
#   for each of the 6 classifiers stays concise and uniform.

def train_evaluate_plot(model_number, model_name, model,
                        X_train, y_train,
                        X_test,  y_test,
                        results_store)
    
    Train a classifier, print its report, draw Confusion Matrix + ROC Curve,
    and append its accuracy to results_store for the final comparison table.

    Parameters
    ----------
    model_number    int   – sequential index (1-6) shown in the header
    model_name      str   – human-readable model label
    model           sklearn-compatible estimator
    X_trainy_train balanced training data (post-SMOTE)
    X_testy_test   original held-out test data (never SMOTE-touched)
    results_store   list  – accumulates {Model ..., Accuracy ...} dicts
    

    # ── STEP 1 Header ────────────────────────────────────────────────────────
    border = =  62
    print(fn{border})
    print(f  Model {model_number} {model_name})
    print(f{border})

    # ── STEP 2 Train ─────────────────────────────────────────────────────────
    print(f[INFO] Training {model_name}...)
    model.fit(X_train, y_train)
    print(f[INFO] Training complete.)

    # ── STEP 3 Predict ───────────────────────────────────────────────────────
    y_pred      = model.predict(X_test)

    # predict_proba() is needed for the ROC curve (probability of class 1)
    # All 6 models are configured with probability=True or support it natively
    y_prob      = model.predict_proba(X_test)[, 1]

    # ── STEP 4 Text-based Classification Report ──────────────────────────────
    acc = accuracy_score(y_test, y_pred)
    print(fn{'─'62})
    print(f  Classification Report — {model_name})
    print(f{'─'62})
    print(classification_report(
        y_test, y_pred,
        target_names=[Phishing (0), Safe (1)],
        digits=4
    ))
    print(f  Overall Accuracy {acc.4f}  ({acc100.2f}%))
    print(f{'─'62})

    # Store accuracy for the final comparison table
    results_store.append({Model model_name, Accuracy (%) round(acc  100, 2)})

    # ── STEP 5 Visualizations — 1×2 subplot ──────────────────────────────────
    fig, axes = plt.subplots(1, 2, figsize=(12, 5))
    fig.patch.set_facecolor(#0F1117)
    fig.suptitle(
        fModel {model_number} {model_name}  ·  Evaluation Dashboard,
        fontsize=14, fontweight=bold, color=white, y=1.01
    )

    ax_cm = axes[0]
    ax_cm.set_facecolor(#181C27)

    cm = confusion_matrix(y_test, y_pred)

    # Annotate each cell with its raw count AND percentage of total test samples
    total       = cm.sum()
    annot_labels = np.array([
        [f{v}n({vtotal100.1f}%) for v in row]
        for row in cm
    ])

    sns.heatmap(
        cm, ax=ax_cm,
        cmap=HEATMAP_CMAP,
        annot=annot_labels, fmt=,
        annot_kws={size 11, weight bold},
        linewidths=1.5, linecolor=#0F1117,
        xticklabels=CLASS_NAMES,
        yticklabels=CLASS_NAMES,
        cbar_kws={shrink 0.75}
    )

    ax_cm.collections[0].colorbar.ax.tick_params(
        colors=#8892B0, labelsize=8
    )

    ax_cm.set_title(Confusion Matrix, fontsize=13, pad=10)
    ax_cm.set_xlabel(Predicted Label, labelpad=8)
    ax_cm.set_ylabel(True Label,      labelpad=8)
    ax_cm.tick_params(axis=x, rotation=15, labelsize=9)
    ax_cm.tick_params(axis=y, rotation=0,  labelsize=9)

    # Highlight diagonal (correct predictions) with a white border
    for i in range(cm.shape[0])
        ax_cm.add_patch(plt.Rectangle(
            (i, i), 1, 1,
            fill=False, edgecolor=white, linewidth=2.0
        ))

    ax_roc = axes[1]
    ax_roc.set_facecolor(#181C27)

    fpr, tpr, _ = roc_curve(y_test, y_prob)
    roc_auc     = auc(fpr, tpr)

    # Shaded area under the ROC curve for visual impact
    ax_roc.fill_between(fpr, tpr, alpha=0.12, color=CLR_ROC)

    # ROC curve line
    ax_roc.plot(
        fpr, tpr,
        color=CLR_ROC, linewidth=2.2,
        label=fAUC = {roc_auc.4f}
    )

    # Random-guess baseline (diagonal dashed line)
    ax_roc.plot(
        [0, 1], [0, 1],
        color=CLR_DIAGONAL, linewidth=1.2,
        linestyle=--, label=Random Guess (AUC = 0.50)
    )

    # Mark the operating point closest to the top-left corner
    # (highest TPR with lowest FPR — the ideal operating point)
    distances   = np.sqrt(fpr2 + (1 - tpr)2)
    best_idx    = np.argmin(distances)
    ax_roc.scatter(
        fpr[best_idx], tpr[best_idx],
        color=#FFFFFF, s=60, zorder=5,
        label=fBest threshold point
    )

    ax_roc.set_title(ROC Curve, fontsize=13, pad=10)
    ax_roc.set_xlabel(False Positive Rate (FPR), labelpad=8)
    ax_roc.set_ylabel(True Positive Rate (TPR), labelpad=8)
    ax_roc.set_xlim([-0.02, 1.02])
    ax_roc.set_ylim([-0.02, 1.05])
    ax_roc.legend(loc=lower right, framealpha=0.88)
    ax_roc.spines[[top, right]].set_visible(False)

    # Accuracy watermark inside ROC panel
    ax_roc.text(
        0.98, 0.10,
        fAccuracy {acc100.2f}%,
        transform=ax_roc.transAxes,
        ha=right, va=bottom,
        fontsize=10, color=#C8D0E7,
        bbox=dict(boxstyle=round,pad=0.35,
                  fc=#1E2235, ec=#2E3350, alpha=0.88)
    )

    # ── STEP 6 Render and move to the next model ─────────────────────────────
    plt.tight_layout()
    plt.show()
    print(f[DONE] {model_name} — graph rendered.n)

# A list that each model appends to; converted to a DataFrame at the end.

results = []

# Baseline linear classifier. Fast to train and highly interpretable.
# C=1.0 is the default regularisation strength (L2 penalty).
# max_iter=1000 to ensure convergence on a large dataset.

lr_model = LogisticRegression(
    C=1.0,
    max_iter=1000,
    random_state=42,
    n_jobs=-1        # use all CPU cores
)

train_evaluate_plot(
    model_number=1,
    model_name=Logistic Regression,
    model=lr_model,
    X_train=X_train_scaled, y_train=y_train,
    X_test=X_test_scaled,   y_test=y_test,
    results_store=results
)

# Non-parametric, instance-based learner.
# n_neighbors=5 balances bias-variance tradeoff for large datasets.
# algorithm='auto' lets sklearn pick the fastest tree structure.

knn_model = KNeighborsClassifier(
    n_neighbors=5,
    algorithm=auto,
    n_jobs=-1
)

train_evaluate_plot(
    model_number=2,
    model_name=K-Nearest Neighbors (KNN),
    model=knn_model,
    X_train=X_train_scaled, y_train=y_train,
    X_test=X_test_scaled,   y_test=y_test,
    results_store=results
)

# Finds the maximum-margin hyperplane separating classes.
# kernel='rbf' handles non-linear boundaries in high-dimensional space.
# probability=True is MANDATORY — it enables predict_proba() for the ROC curve.
# Note SVM is memory-intensive; cache_size=500 MB improves kernel caching.

svm_model = SVC(
    kernel=rbf,
    C=1.0,
    gamma=scale,      # auto-scales to 1(n_features  X.var())
    probability=True,   # REQUIRED for predict_proba() and ROC plotting
    cache_size=500,
    random_state=42
)

train_evaluate_plot(
    model_number=3,
    model_name=Support Vector Machine (SVM),
    model=svm_model,
    X_train=X_train_scaled, y_train=y_train,
    X_test=X_test_scaled,   y_test=y_test,
    results_store=results
)

# Feed-forward multi-layer perceptron with two hidden layers.
# hidden_layer_sizes=(64, 32) 64 neurons → 32 neurons → output layer.
# activation='relu' avoids vanishing gradients (faster convergence than tanh).
# early_stopping=True halts training when validation loss plateaus, saving time.

ann_model = MLPClassifier(
    hidden_layer_sizes=(64, 32),
    activation=relu,
    solver=adam,
    alpha=0.0001,          # L2 regularisation to reduce overfitting
    learning_rate=adaptive,
    max_iter=500,
    early_stopping=True,   # stops early if val loss doesn't improve
    validation_fraction=0.1,
    random_state=42
)

train_evaluate_plot(
    model_number=4,
    model_name=Artificial Neural Network (ANN — MLP),
    model=ann_model,
    X_train=X_train_scaled, y_train=y_train,
    X_test=X_test_scaled,   y_test=y_test,
    results_store=results
)

# Ensemble of 100 decision trees trained on bootstrap samples.
# max_features='sqrt' is standard for classification (reduces correlation).
# n_jobs=-1 parallelises tree building across all CPU cores.

rf_model = RandomForestClassifier(
    n_estimators=100,
    max_features=sqrt,
    min_samples_split=2,
    random_state=42,
    n_jobs=-1
)

train_evaluate_plot(
    model_number=5,
    model_name=Random Forest,
    model=rf_model,
    X_train=X_train_scaled, y_train=y_train,
    X_test=X_test_scaled,   y_test=y_test,
    results_store=results
)

# Gradient-boosted tree ensemble — typically top-performer on tabular data.
# eval_metric='logloss' suppresses the default deprecation warning.
# use_label_encoder=False disables the legacy sklearn label encoder.
# scale_pos_weight is not set here because SMOTE already balanced the classes.

xgb_model = XGBClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=6,
    subsample=0.8, colsample_bytree=0.8,
    use_label_encoder=False, eval_metric=logloss,
    random_state=42, n_jobs=-1
)
train_evaluate_plot(
    model_number=6, model_name=XGBoost,model=xgb_model,
    X_train=X_train_scaled, y_train=y_train,
    X_test=X_test_scaled,   y_test=y_test, results_store=results
)

# Convert the accumulated results list into a ranked summary DataFrame.

print(n + =  62)
print(  FINAL MODEL COMPARISON — Accuracy Summary)
print(=  62)

comparison_df = (
    pd.DataFrame(results)
    .sort_values(Accuracy (%), ascending=False)
    .reset_index(drop=True)
)

# 1-based rank column
comparison_df.index = comparison_df.index + 1
comparison_df.index.name = Rank

# Highlight the best model
best_model = comparison_df.iloc[0][Model]
best_acc   = comparison_df.iloc[0][Accuracy (%)]

print(comparison_df.to_string())
print()
print(f  Best Performing Model  {best_model})
print(f  Best Accuracy          {best_acc.2f}%)
print(=  62)

# XAI-Powered Phishing URL Detection System
#
# HOW TO INTEGRATE WITH STEP 3 (Model Training)
#   Option A (Recommended) Replace the `results` list in Step 3 with the
#   `model_results` list defined below, or simply append this script after
#   the training script — the `results` list is already populated.
#
#   Option B (Standalone) The `model_results` list at the top of this file
#   contains realistic placeholder metrics. Swap in your real values and run.

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.ticker as mticker
import seaborn as sns
import warnings
warnings.filterwarnings(ignore)

# ── Scikit-learn metrics (used to compute per-model scores) ───────────────────
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
)


plt.rcParams.update({
    figure.facecolor  #0F1117,
    axes.facecolor    #181C27,
    axes.edgecolor    #2E3350,
    axes.labelcolor   #C8D0E7,
    axes.titlecolor   #FFFFFF,
    axes.titlesize    14,
    axes.labelsize    11,
    axes.titleweight  bold,
    axes.grid         True,
    grid.color        #2E3350,
    grid.linestyle    --,
    grid.alpha        0.45,
    xtick.color       #8892B0,
    ytick.color       #8892B0,
    xtick.labelsize   10,
    ytick.labelsize   10,
    text.color        #C8D0E7,
    legend.facecolor  #1E2235,
    legend.edgecolor  #2E3350,
    legend.fontsize   10,
    font.family       DejaVu Sans,
})

# Colour tokens
CLR_WINNER   = #00E5B0   # teal-green  — winning model highlight
CLR_DEFAULT  = #7B8CDE   # soft indigo — all other bars
CLR_ACCENT   = #FF4B6E   # coral-red   — accent  secondary metrics
METRIC_PALETTE = [          # one colour per metric in the grouped chart
    #7B8CDE,   # Accuracy   — indigo
    #00E5B0,   # Precision  — teal
    #FFB347,   # Recall     — amber
    #FF4B6E,   # F1-Score   — coral
]

METRICS = [Accuracy, Precision, Recall, F1-Score]


# If you ran Step 3, replace the block below with the real predictions that
# are already in memory.  The helper function compute_metrics() accepts
# (y_true, y_pred) arrays and returns a tidy dict — call it once per model.
#
# STANDALONE MODE edit the values inside `model_results` to match your
# actual classification report numbers, then run this script on its own.

def compute_metrics(model_name, y_true, y_pred)
    
    Compute the four key classification metrics for one model and return
    them as a dictionary that feeds directly into the comparison DataFrame.
    
    return {
        Model     model_name,
        Accuracy  round(accuracy_score (y_true, y_pred),                         4),
        Precision round(precision_score(y_true, y_pred, average=weighted,
                                           zero_division=0),                         4),
        Recall    round(recall_score   (y_true, y_pred, average=weighted,
                                           zero_division=0),                         4),
        F1-Score  round(f1_score       (y_true, y_pred, average=weighted,
                                           zero_division=0),                         4),
    }


# ── STANDALONE PLACEHOLDER METRICS ───────────────────────────────────────────
# Replace these with calls to compute_metrics() once real y_pred arrays exist,
# e.g. model_results = [compute_metrics(LR, y_test, lr_pred), ...]
model_results = [
    {Model Logistic Regression,          Accuracy 0.9421, Precision 0.9425, Recall 0.9421, F1-Score 0.9420},
    {Model K-Nearest Neighbors (KNN),    Accuracy 0.9683, Precision 0.9685, Recall 0.9683, F1-Score 0.9683},
    {Model Support Vector Machine (SVM), Accuracy 0.9754, Precision 0.9756, Recall 0.9754, F1-Score 0.9754},
    {Model ANN (MLP),                    Accuracy 0.9812, Precision 0.9813, Recall 0.9812, F1-Score 0.9812},
    {Model Random Forest,                Accuracy 0.9891, Precision 0.9892, Recall 0.9891, F1-Score 0.9891},
    {Model XGBoost,                      Accuracy 0.9934, Precision 0.9935, Recall 0.9934, F1-Score 0.9934},
]

# Uncomment the four lines below and comment out the placeholder block above
# once the real training variables (models + y_test + predictions) are present
#
# model_results = [
#     compute_metrics(Logistic Regression,          y_test, lr_pred),
#     compute_metrics(K-Nearest Neighbors (KNN),    y_test, knn_pred),
#     compute_metrics(Support Vector Machine (SVM), y_test, svm_pred),
#     compute_metrics(ANN (MLP),                    y_test, ann_pred),
#     compute_metrics(Random Forest,                y_test, rf_pred),
#     compute_metrics(XGBoost,                      y_test, xgb_pred),
# ]


print(n + =  68)
print(  SECTION 1 — Comprehensive Model Metrics Table)
print(=  68)

# Build the master DataFrame and sort by Accuracy (descending)
metrics_df = (
    pd.DataFrame(model_results)
    .sort_values(Accuracy, ascending=False)
    .reset_index(drop=True)
)
metrics_df.index = metrics_df.index + 1      # 1-based rank
metrics_df.index.name = Rank

# Convert raw [0-1] scores to percentage strings for clean display
display_df = metrics_df.copy()
for col in METRICS
    display_df[col] = display_df[col].apply(lambda v f{v100.2f}%)

# Print with consistent column width
col_widths = {Model 32, Accuracy 10, Precision 10,
              Recall 8, F1-Score 10}
header = (f{'Rank'5} {'Model'32} {'Accuracy'10} 
          f{'Precision'10} {'Recall'8} {'F1-Score'10})
sep    = -  len(header)

print(fn{header})
print(sep)
for rank, row in display_df.iterrows()
    print(f{rank5} {row['Model']32} {row['Accuracy']10} 
          f{row['Precision']10} {row['Recall']8} {row['F1-Score']10})
print(sep)
print()

# SECTION 2 — GRAPH 1 Accuracy Comparison Bar Chart (sorted, winner highlighted)

print(=  68)
print(  SECTION 2A — Graph 1 Accuracy Comparison Bar Chart)
print(=  68)

# Sort so the tallest bar is on the left for a clean descending waterfall look
acc_df       = metrics_df.sort_values(Accuracy, ascending=False).reset_index(drop=True)
best_acc_idx = acc_df[Accuracy].idxmax()   # index of the winner (always 0 after sort)

# Assign colours teal for winner, indigo for the rest
bar_colours = [
    CLR_WINNER if i == best_acc_idx else CLR_DEFAULT
    for i in range(len(acc_df))
]

fig1, ax1 = plt.subplots(figsize=(12, 6))
fig1.patch.set_facecolor(#0F1117)
ax1.set_facecolor(#181C27)

bars = ax1.bar(
    acc_df[Model],
    acc_df[Accuracy]  100,    # display as percentage
    color=bar_colours,
    edgecolor=#0F1117,
    linewidth=1.2,
    width=0.55,
    zorder=3
)

# ── Data labels on top of every bar ──────────────────────────────────────────
for bar, colour in zip(bars, bar_colours)
    height = bar.get_height()
    ax1.text(
        bar.get_x() + bar.get_width()  2,
        height + 0.08,                       # small gap above the bar
        f{height.2f}%,
        ha=center, va=bottom,
        fontsize=10, fontweight=bold,
        color=colour
    )

# ── Winner star annotation ────────────────────────────────────────────────────
winner_bar = bars[best_acc_idx]
ax1.annotate(
    ★  Best,
    xy=(winner_bar.get_x() + winner_bar.get_width()  2,
        winner_bar.get_height() + 0.65),
    ha=center, va=bottom,
    fontsize=11, color=CLR_WINNER, fontweight=bold
)

# ── Axes formatting ───────────────────────────────────────────────────────────
ax1.set_title(Model Accuracy Comparison  ·  Sorted Highest → Lowest,
              fontsize=15, pad=18)
ax1.set_ylabel(Accuracy (%), labelpad=10)
ax1.set_xlabel(Classifier, labelpad=10)

# Tight y-range so small differences are visible
y_min = max(0, acc_df[Accuracy].min()  100 - 2.0)
y_max = min(100, acc_df[Accuracy].max()  100 + 2.5)
ax1.set_ylim(y_min, y_max)
ax1.yaxis.set_major_formatter(mticker.FormatStrFormatter(%.1f%%))

ax1.tick_params(axis=x, rotation=15, labelsize=9)
ax1.spines[[top, right]].set_visible(False)

legend_handles = [
    mpatches.Patch(color=CLR_WINNER,  label=Best Performing Model),
    mpatches.Patch(color=CLR_DEFAULT, label=Other Models),
]
ax1.legend(handles=legend_handles, loc=lower right, framealpha=0.90)

# Light horizontal reference line at the winner's accuracy
ax1.axhline(
    acc_df[Accuracy].max()  100,
    color=CLR_WINNER, linewidth=1.0,
    linestyle=--, alpha=0.35, zorder=2
)

fig1.text(0.99, 0.01,
          PhiUSIIL Phishing URL Detection    Model Comparison,
          ha=right, va=bottom,
          fontsize=8, color=#3D4566, style=italic)

plt.tight_layout()
plt.show()
print([DONE] Graph 1 rendered.n)


print(=  68)
print(  SECTION 2B — Graph 2 Grouped Metrics Comparison Chart)
print(=  68)

# Melt the DataFrame from wide → long format so seaborn can group bars
plot_df = (
    metrics_df.copy()
    .melt(id_vars=Model, value_vars=METRICS,
          var_name=Metric, value_name=Score)
)

# Sort models by Accuracy (descending) for consistent left-to-right ordering
model_order = metrics_df.sort_values(Accuracy, ascending=False)[Model].tolist()

fig2, ax2 = plt.subplots(figsize=(15, 7))
fig2.patch.set_facecolor(#0F1117)
ax2.set_facecolor(#181C27)

# Map each metric to its brand colour
metric_palette = {m c for m, c in zip(METRICS, METRIC_PALETTE)}

sns.barplot(
    data=plot_df,
    x=Model, y=Score,
    hue=Metric,
    palette=metric_palette,
    order=model_order,
    edgecolor=#0F1117,
    linewidth=0.8,
    width=0.75,
    ax=ax2,
    zorder=3
)

# ── Data labels on every grouped bar ─────────────────────────────────────────
for container in ax2.containers
    ax2.bar_label(
        container,
        fmt=%.2f,            # two decimal places (e.g. 0.99)
        label_type=edge,
        fontsize=7.0,
        fontweight=bold,
        color=#C8D0E7,
        padding=2
    )

# ── Axes formatting ───────────────────────────────────────────────────────────
ax2.set_title(Detailed Metrics Comparison  ·  All 6 Models × 4 Metrics,
              fontsize=15, pad=18)
ax2.set_ylabel(Score  (0 – 1), labelpad=10)
ax2.set_xlabel(Classifier, labelpad=10)

y_min2 = max(0.0, plot_df[Score].min() - 0.02)
ax2.set_ylim(y_min2, 1.04)
ax2.yaxis.set_major_formatter(mticker.FormatStrFormatter(%.2f))

ax2.tick_params(axis=x, rotation=12, labelsize=9)
ax2.spines[[top, right]].set_visible(False)

# Move legend outside the plot area so it doesn't obscure bars
ax2.legend(
    title=Metric, title_fontsize=10,
    loc=lower right,
    framealpha=0.90,
    ncol=2
)

winner_name = metrics_df.iloc[0][Model]   # top row after sort
winner_pos  = model_order.index(winner_name)
ax2.axvspan(
    winner_pos - 0.45, winner_pos + 0.45,
    alpha=0.07, color=CLR_WINNER, zorder=0
)
ax2.text(
    winner_pos, ax2.get_ylim()[1]  0.995,
    ★  Best,
    ha=center, va=top,
    fontsize=10, color=CLR_WINNER, fontweight=bold
)

fig2.text(0.99, 0.01,
          PhiUSIIL Phishing URL Detection    Model Comparison,
          ha=right, va=bottom,
          fontsize=8, color=#3D4566, style=italic)

plt.tight_layout()
plt.show()
print([DONE] Graph 2 rendered.n)


print(=  68)
print(  SECTION 3 — Best Model Selection)
print(=  68)

# Programmatically find the row with the maximum Accuracy — no hard-coding
best_row             = metrics_df.loc[metrics_df[Accuracy].idxmax()]
final_best_model_name = best_row[Model]           # ← used in Step 5 (SHAP  XAI)
best_accuracy        = best_row[Accuracy]  100
best_precision       = best_row[Precision]  100
best_recall          = best_row[Recall]     100
best_f1              = best_row[F1-Score]   100

# Runner-up (second-best) for context
runner_up_row  = metrics_df.iloc[1]
runner_up_name = runner_up_row[Model]
margin         = best_accuracy - runner_up_row[Accuracy]  100

# ── Professional winner announcement ─────────────────────────────────────────
print()
print(┌ + ─  66 + ┐)
print(│ +    66 + │)
print(│   WINNING MODEL DECLARATION                               │)
print(│ +    66 + │)
print(f│  The Best Model is    {final_best_model_name40}│)
print(│ +    66 + │)
print(f│  Accuracy   {best_accuracy6.2f}%                                        │)
print(f│  Precision  {best_precision6.2f}%                                        │)
print(f│  Recall     {best_recall6.2f}%                                        │)
print(f│  F1-Score   {best_f16.2f}%                                        │)
print(│ +    66 + │)
print(f│  Margin over runner-up ({runner_up_name22}) +{margin.2f}%  │)
print(│ +    66 + │)
print(└ + ─  66 + ┘)

# ── Programmatic winner variable (used downstream in SHAP  XAI step) ────────
print(fn[EXPORT] final_best_model_name = '{final_best_model_name}')
print([INFO]   This variable is ready for use in Step 5 Explainable AI (SHAP).)
print()

# ── Quick ranked summary ──────────────────────────────────────────────────────
print(  Full Accuracy Ranking)
print(   + ─  50)
for rank, (_, row) in enumerate(metrics_df.iterrows(), start=1)
    trophy = 1 if rank == 1 else (2 if rank == 2 else (3 if rank == 3 else f  {rank}.))
    print(f  {trophy}  {row['Model']35} {row['Accuracy']100.2f}%)
print(   + ─  50)
print()
print(=  68)
print(  Step 4 Complete — Final Best Model selected and ready for XAI.)
print(=  68)

# XAI-Powered Phishing URL Detection System
#
# Prerequisites (must be in environment from previous steps)
#   xgb_model      → trained XGBClassifier (the winning model)
#   X_train_scaled → scaled training DataFrame (with feature names)
#   X_test_scaled  → scaled test DataFrame    (with feature names)
#   y_test         → true test labels (pandas Series)
#   scaler         → fitted StandardScaler object

# ── Core libraries ─────────────────────────────────────────────────────────────
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.gridspec as gridspec
import seaborn as sns
import joblib
import shap
import warnings
warnings.filterwarnings(ignore)


plt.rcParams.update({
    figure.facecolor  #0F1117,
    axes.facecolor    #181C27,
    axes.edgecolor    #2E3350,
    axes.labelcolor   #C8D0E7,
    axes.titlecolor   #FFFFFF,
    axes.titlesize    14,
    axes.labelsize    11,
    axes.titleweight  bold,
    axes.grid         True,
    grid.color        #2E3350,
    grid.linestyle    --,
    grid.alpha        0.40,
    xtick.color       #8892B0,
    ytick.color       #8892B0,
    xtick.labelsize   10,
    ytick.labelsize   10,
    text.color        #C8D0E7,
    legend.facecolor  #1E2235,
    legend.edgecolor  #2E3350,
    legend.fontsize   10,
    font.family       DejaVu Sans,
})

CLR_PHISHING = #FF4B6E   # coral-red  → malicious signal
CLR_SAFE     = #00E5B0   # teal-green → benign signal
CLR_NEUTRAL  = #7B8CDE   # indigo     → neutral bars


# Build the SHAP TreeExplainer and compute SHAP values for the test set.

print(n + =  66)
print(  SECTION 1 — SHAP Explainer Initialisation)
print(=  66)

# ── 1A. Ensure X_test_scaled is a proper DataFrame with feature names ─────────
# SHAP requires feature names for readable axis labels on all plots.
# If X_test_scaled is already a DataFrame (as set up in Step 2), this is a
# safe no-op. If it is a numpy array, we reconstruct column names from the
# scaler or the training DataFrame.

if not isinstance(X_test_scaled, pd.DataFrame)
    print([WARN] X_test_scaled is not a DataFrame — rebuilding with feature names.)
    feature_names = (
        X_train_scaled.columns.tolist()
        if isinstance(X_train_scaled, pd.DataFrame)
        else [ffeature_{i} for i in range(X_test_scaled.shape[1])]
    )
    X_test_scaled = pd.DataFrame(X_test_scaled, columns=feature_names)
    print(f[INFO] Rebuilt DataFrame with {len(feature_names)} named columns.)
else
    print(f[INFO] X_test_scaled is already a DataFrame — {X_test_scaled.shape[1]} features.)

feature_names = X_test_scaled.columns.tolist()
print(f[INFO] Feature names confirmed {feature_names[5]} ... (total {len(feature_names)}))

# ── 1B. Initialise SHAP TreeExplainer ────────────────────────────────────────
# TreeExplainer is the correct explainer for tree-based models (XGBoost,
# RandomForest, LightGBM). It computes exact Shapley values in polynomial
# time by exploiting the tree structure — far faster than KernelExplainer.
print(n[INFO] Initialising shap.TreeExplainer for XGBoost...)
explainer = shap.TreeExplainer(xgb_model)
print([INFO] TreeExplainer ready.)

# ── 1C. Calculate SHAP values for the entire test set ─────────────────────────
# shap_values is a 2D array of shape (n_samples, n_features).
# Each cell [i, j] = how much feature j pushed sample i's prediction
#   away from the base rate (positive = towards phishing, negative = towards safe).
# We use check_additivity=False to suppress a strict sum check that can
# occasionally trigger a floating-point mismatch warning in older XGBoost builds.
print([INFO] Computing SHAP values for the full test set (this may take ~30s)...)
shap_values = explainer.shap_values(X_test_scaled, check_additivity=False)

# For binary classification XGBoost returns a single matrix (class-1 SHAP values)
# For multi-output models it returns a list — normalise to always be a 2D array
if isinstance(shap_values, list)
    # Take index [1] = SHAP values for the positive class (Phishing = 1)
    shap_values = shap_values[1]

print(f[INFO] SHAP values computed — shape {shap_values.shape})
print(f[INFO] Base value (expected model output) 
      f{explainer.expected_value if np.isscalar(explainer.expected_value) else explainer.expected_value[1].4f})

# Shows the TOP FEATURES that drive predictions across the ENTIRE test set.

print(n + =  66)
print(  SECTION 2 — Graph 1 Global Feature Importance (SHAP Summary))
print(=  66)
print([INFO] Generating SHAP Global Summary Bar Plot...)

# Mean absolute SHAP value per feature = average impact on model output magnitude
mean_abs_shap    = np.abs(shap_values).mean(axis=0)
shap_importance  = pd.DataFrame({
    Feature    feature_names,
    SHAP_Value mean_abs_shap
}).sort_values(SHAP_Value, ascending=False).reset_index(drop=True)

TOP_N = 20     # show the 20 most impactful features
top_df = shap_importance.head(TOP_N)

fig1, ax1 = plt.subplots(figsize=(13, 8))
fig1.patch.set_facecolor(#0F1117)
ax1.set_facecolor(#181C27)

# Colour gradient strongest features in coral, weakest in indigo
colours = [
    plt.cm.RdYlGn_r(i  (TOP_N - 1))    # red → yellow → green (reversed)
    for i in range(TOP_N)
]

bars = ax1.barh(
    top_df[Feature][-1],           # reverse so rank-1 is at the top
    top_df[SHAP_Value][-1],
    color=colours[-1],
    edgecolor=#0F1117,
    linewidth=0.8,
    height=0.65
)

# Annotate each bar with its exact SHAP value
for bar in bars
    width = bar.get_width()
    ax1.text(
        width + 0.0005,
        bar.get_y() + bar.get_height()  2,
        f{width.4f},
        va=center, ha=left,
        fontsize=8.5, color=#C8D0E7
    )

ax1.set_title(
    Global Feature Importance  ·  SHAP Mean φ Valuesn
    fTop {TOP_N} Features driving XGBoost predictions (entire test set),
    fontsize=14, pad=14
)
ax1.set_xlabel(Mean SHAP Value  —  Average impact on model output magnitude, labelpad=10)
ax1.set_ylabel(Feature, labelpad=10)
ax1.spines[[top, right]].set_visible(False)
ax1.tick_params(axis=y, labelsize=9)

# Colour scale legend
from matplotlib.cm import ScalarMappable
from matplotlib.colors import Normalize
sm  = ScalarMappable(cmap=RdYlGn_r, norm=Normalize(vmin=0, vmax=TOP_N - 1))
sm.set_array([])
cbar = fig1.colorbar(sm, ax=ax1, shrink=0.55, pad=0.02)
cbar.set_label(Feature Rank  (top → bottom), color=#8892B0, fontsize=9)
cbar.ax.tick_params(colors=#8892B0, labelsize=8)
cbar.set_ticks([0, TOP_N - 1])
cbar.set_ticklabels([Rank 1n(Most important), fRank {TOP_N}n(Least of top-{TOP_N})])

fig1.text(0.99, 0.01,
          PhiUSIIL Phishing URL Detection    XAI — SHAP Global Analysis,
          ha=right, va=bottom, fontsize=8, color=#3D4566, style=italic)

plt.tight_layout()
plt.show()
print([DONE] Graph 1 (Global SHAP Summary) rendered.n)

# Unlike the bar chart above, this canonical SHAP plot shows EACH individual
# test-set prediction as a dot, coloured by feature value (red = high, blue = low).
# It reveals whether a feature's high value pushes towards phishing or safe.

print(=  66)
print(  SECTION 3 — Graph 2a SHAP Beeswarm  Dot Summary Plot)
print(=  66)
print([INFO] Generating SHAP Beeswarm Plot (feature direction + distribution)...)

# Restrict to top 15 features for a clean, uncluttered plot
top15_features = shap_importance[Feature].head(15).tolist()
top15_idx      = [feature_names.index(f) for f in top15_features]

shap_top15 = shap_values[, top15_idx]
X_top15    = X_test_scaled[top15_features]

fig2, ax2 = plt.subplots(figsize=(13, 8))
fig2.patch.set_facecolor(#0F1117)
ax2.set_facecolor(#181C27)

# shap.summary_plot draws directly onto the current matplotlib axes
shap.summary_plot(
    shap_top15,
    X_top15,
    plot_type=dot,          # 'dot' = beeswarm (one dot per sample)
    max_display=15,
    show=False,               # prevent SHAP from calling plt.show() internally
    color_bar=True,
    plot_size=None            # let our figsize control dimensions
)

# Re-style after SHAP draws (it overwrites some rcParams internally)
ax2 = plt.gca()
ax2.set_facecolor(#181C27)
ax2.tick_params(colors=#8892B0, labelsize=9)
ax2.set_xlabel(SHAP Value  (positive → Phishing  negative → Safe), color=#C8D0E7, labelpad=10)
ax2.set_title(
    SHAP Beeswarm Plot  ·  Feature Value Direction & Distributionn
    Top 15 Features    Each dot = one test-set URL,
    color=white, fontsize=13, pad=12
)

fig2.patch.set_facecolor(#0F1117)
fig2.text(0.99, 0.01,
          PhiUSIIL Phishing URL Detection    XAI — SHAP Beeswarm Analysis,
          ha=right, va=bottom, fontsize=8, color=#3D4566, style=italic)

plt.tight_layout()
plt.show()
print([DONE] Graph 2a (SHAP Beeswarm) rendered.n)

# SECTION 4 — GRAPH 2b Local Explainability — Waterfall Plot for ONE Phishing URL

print(=  66)
print(  SECTION 4 — Graph 2b Local Explainability (Single Phishing Prediction))
print(=  66)

# ── 4A. Find exactly ONE confirmed True-Positive Phishing URL ─────────────────
# Strategy we need a sample where
#   actual label  == 1  (truly a phishing URL)
# This is the most instructive case because it explains a CORRECT detection.

y_test_arr   = np.array(y_test)
y_pred_arr   = xgb_model.predict(X_test_scaled)

# Boolean mask both the true label and predicted label must be 1 (Phishing)
tp_mask      = (y_test_arr == 1) & (y_pred_arr == 1)
tp_indices   = np.where(tp_mask)[0]

if len(tp_indices) == 0
    raise RuntimeError(
        [ERROR] No True-Positive Phishing samples found in X_test_scaled. 
        Check that y_test uses label 1 for phishing and the model is loaded correctly.
    )

# Pick the first true-positive for reproducibility
sample_idx      = tp_indices[0]
sample_row      = X_test_scaled.iloc[[sample_idx]]   # keep as DataFrame (1 row)
sample_shap     = shap_values[sample_idx]            # 1D array — SHAP values for this URL

print(f[INFO] Selected sample index {sample_idx})
print(f[INFO] True label       Phishing (1))
print(f[INFO] Model prediction Phishing (1)  ← True Positive ✓)
print(f[INFO] Model confidence 
      f{xgb_model.predict_proba(sample_row)[0][1]100.2f}% phishing probability)

# ── 4B. Build a SHAP Explanation object for the waterfall plot ────────────────
# shap.Explanation wraps (values, base_values, data, feature_names) into a
# single object that the new-style shap.plots.waterfall() expects.

base_val = (
    explainer.expected_value
    if np.isscalar(explainer.expected_value)
    else explainer.expected_value[1]
)

shap_explanation = shap.Explanation(
    values        = sample_shap,
    base_values   = base_val,
    data          = sample_row.values[0],
    feature_names = feature_names
)

# ── 4C. Waterfall Plot ────────────────────────────────────────────────────────
print(n[INFO] Generating SHAP Waterfall Plot for the selected Phishing URL...)

fig3, ax3 = plt.subplots(figsize=(13, 9))
fig3.patch.set_facecolor(#0F1117)

# Draw waterfall onto the current figure (show=False prevents early rendering)
shap.plots.waterfall(
    shap_explanation,
    max_display=15,    # show top 15 contributors (positive + negative)
    show=False
)

ax3 = plt.gca()
ax3.set_facecolor(#181C27)
ax3.tick_params(colors=#8892B0, labelsize=9)
fig3.patch.set_facecolor(#0F1117)

# Override the default title with a richer, context-aware one
plt.suptitle(
    fLocal Explanation  ·  Single Phishing URL  (Test Sample #{sample_idx})n
    fSHAP Waterfall Plot    Model Confidence 
    f{xgb_model.predict_proba(sample_row)[0][1]100.2f}% Phishing,
    fontsize=13, fontweight=bold, color=white, y=1.01
)

fig3.text(0.99, 0.01,
          PhiUSIIL Phishing URL Detection    XAI — SHAP Local Analysis,
          ha=right, va=bottom, fontsize=8, color=#3D4566, style=italic)

plt.tight_layout()
plt.show()
print([DONE] Graph 2b (SHAP Waterfall) rendered.n)

# ── 4D. Plain-English Reasoning for This Specific URL ────────────────────────
# Sort features by their SHAP magnitude for this sample so we can narrate
# the top drivers in a human-readable format.

local_df = (
    pd.DataFrame({
        Feature     feature_names,
        SHAP_Value  sample_shap,
        Feature_Val sample_row.values[0]
    })
    .reindex(columns=[Feature, SHAP_Value, Feature_Val])
    .assign(Direction=lambda d d[SHAP_Value].apply(
        lambda v ⬆ pushes PHISHING if v  0 else ⬇ pushes SAFE
    ))
    .sort_values(SHAP_Value, key=abs, ascending=False)
    .reset_index(drop=True)
)

top_phishing_drivers = local_df[local_df[SHAP_Value]  0].head(3)
top_safe_drivers     = local_df[local_df[SHAP_Value]  0].head(2)

print(─  66)
print(    PLAIN-ENGLISH EXPLANATION FOR TEST SAMPLE #{,}.format(sample_idx))
print(─  66)
print(
    fn  This URL was classified as PHISHING with 
    f{xgb_model.predict_proba(sample_row)[0][1]100.2f}% confidence.n
)
print(  TOP FEATURES pushing this URL toward PHISHING (coral bars ↑))
for _, row in top_phishing_drivers.iterrows()
    print(f   • '{row['Feature']}' had a scaled value of 
          f{row['Feature_Val'].4f} and pushed the prediction 
          fTOWARDS PHISHING by +{row['SHAP_Value'].4f} SHAP units.)

print()
print(  TOP FEATURES pushing AGAINST phishing classification (teal bars ↓))
if len(top_safe_drivers) == 0
    print(   • No features pushed meaningfully toward Safe — 
          this URL has almost no benign signals.)
else
    for _, row in top_safe_drivers.iterrows()
        print(f   • '{row['Feature']}' had a scaled value of 
              f{row['Feature_Val'].4f} and pushed the prediction 
              fTOWARDS SAFE by {row['SHAP_Value'].4f} SHAP units.)

print()
print(
    f  ➜  Despite any minor Safe signals, the combined weight of then
    f     phishing-driving features overwhelms them, resulting in an
    f     high-confidence PHISHING classification.n
)
print(─  66)


print(n + =  66)
print(  SECTION 5 — Production Export Model & Scaler Serialisation)
print(=  66)

MODEL_PATH  = best_phishing_model.pkl
SCALER_PATH = scaler.pkl

# ── Save the trained XGBoost model ────────────────────────────────────────────
# joblib is preferred over pickle for large numpy arrays (used internally by
# sklearn  XGBoost) because it serialises them more efficiently with
# optional compression. compress=3 gives a good sizespeed trade-off.
print(fn[INFO] Saving XGBoost model  → '{MODEL_PATH}' ...)
joblib.dump(xgb_model, MODEL_PATH, compress=3)
print(f[OK]   Model saved successfully.)

# ── Save the StandardScaler ────────────────────────────────────────────────────
# CRITICAL The scaler MUST be saved alongside the model.
# Any incoming raw URL feature vector in the Flask API  Splunk pipeline
# must be scaled with the SAME scaler (same mean_ and scale_ arrays) that
# was fitted on the training data. Using a fresh scaler would produce
# completely wrong z-scores and destroy model accuracy in production.
print(fn[INFO] Saving StandardScaler → '{SCALER_PATH}' ...)
joblib.dump(scaler, SCALER_PATH, compress=3)
print(f[OK]   Scaler saved successfully.)

# ── Verify the saved files load correctly (round-trip check) ─────────────────
print(fn[INFO] Running round-trip verification...)

loaded_model  = joblib.load(MODEL_PATH)
loaded_scaler = joblib.load(SCALER_PATH)

# Quick sanity check predictions from the loaded model must match originals
original_preds = xgb_model.predict(X_test_scaled[10])
loaded_preds   = loaded_model.predict(X_test_scaled[10])
scaler_match   = np.allclose(loaded_scaler.mean_, scaler.mean_)

assert np.array_equal(original_preds, loaded_preds), 
    CRITICAL Loaded model predictions do not match original model!
assert scaler_match, 
    CRITICAL Loaded scaler mean_ does not match original scaler!

print(f[OK]   Model round-trip check  → PASSED ✓ (1010 predictions match))
print(f[OK]   Scaler round-trip check → PASSED ✓ (mean_ arrays identical))

# ── Final success banner ───────────────────────────────────────────────────────
print()
print(┌ + ─  64 + ┐)
print(│                                                                │)
print(│      PRODUCTION EXPORT COMPLETE                               │)
print(│                                                                │)
print(f│     best_phishing_model.pkl  → Trained XGBoost classifier   │)
print(f│     scaler.pkl               → Fitted StandardScaler         │)
print(│                                                                │)
print(│   Both files are verified and ready for                       │)
print(│     • Flask REST API  (predict endpoint)                       │)
print(│     • Splunk MLTK    (real-time URL scoring)                   │)
print(│     • CICD pipeline (model registry upload)                   │)
print(│                                                                │)
print(└ + ─  64 + ┘)
print()

# ── Usage snippet for the downstream Flask API ─────────────────────────────────
print(  USAGE IN FLASK API  PRODUCTION)
print(  ─  33)
print(
  import joblib, pandas as pd

  model  = joblib.load('best_phishing_model.pkl')
  scaler = joblib.load('scaler.pkl')

  def predict_url(feature_dict dict) - dict
      # feature_dict = raw extracted URL features (unscaled)
      raw_df  = pd.DataFrame([feature_dict])
      scaled  = scaler.transform(raw_df)
      prob    = model.predict_proba(scaled)[0][1]
      label   = PHISHING if prob = 0.5 else SAFE
      return {label label, phishing_probability round(prob, 4)}
)
print(=  66)
print(  Step 5 Complete — XAI analysis done, production artifacts exported.)
print(=  66)

# Export & Download Cleaned Preprocessed Dataset
# Google Colab — Run this cell after your preprocessing pipeline is complete.

import pandas as pd
from google.colab import files

# We use X (the post-multicollinearity-removal features, BEFORE scaling) so the
# CSV contains human-readable original-scale values — not z-scores.
# The target column 'label' is added back as the final column.
#
# If you prefer the scaled version, swap X for X_train_scaled  X_test_scaled.

cleaned_dataset = X.copy()          # all cleaned features (no dropped text cols,
                                    # no correlated cols, no scaling)
cleaned_dataset[label] = y.values # attach the original target labels

print(fDataset shape   {cleaned_dataset.shape})
print(fColumns         {list(cleaned_dataset.columns[5])} ... (total {len(cleaned_dataset.columns)}))
print(fLabel distributionn{cleaned_dataset['label'].value_counts().to_string()})


FILE_NAME = Cleaned_PhiUSIIL_Dataset.csv

cleaned_dataset.to_csv(FILE_NAME, index=False)   # index=False prevents an
                                                  # unwanted row-number column
print(fn[OK] '{FILE_NAME}' saved to Colab runtime ({cleaned_dataset.shape[0],} rows).)


files.download(FILE_NAME)
print(f[OK] Download triggered — check your browser's Downloads folder.)

# ── Cell 1 Install dependencies ──────────────────────────────────────────────
# Run this cell first, then run Cell 2 in a separate Colab cell.
!pip install flask pyngrok shap xgboost joblib --quiet

# Phishing URL Detection System — Flask REST API
# Runs inside Google Colab via pyngrok tunnel on port 5000.
#
# BEFORE RUNNING
#   1. Upload best_phishing_model.pkl and scaler.pkl to your Colab runtime.
#   2. Get your free ngrok auth token from httpsdashboard.ngrok.com
#   3. Paste it in the NGROK_AUTH_TOKEN variable below.


# ── Cell 2 Full Flask API ────────────────────────────────────────────────────

import os
import json
import joblib
import numpy as np
import pandas as pd
import shap
import threading

from flask       import Flask, request, jsonify
from pyngrok     import ngrok, conf
from datetime    import datetime


# ── Paste your free ngrok auth token here ────────────────────────────────────
# Get it from httpsdashboard.ngrok.comget-startedyour-authtoken
NGROK_AUTH_TOKEN = 3Avt8hUtkJRzZtaDpHqQD4NB9Bs_5AFAPRSAv62cU3aW9NTUL

PORT             = 5000
MODEL_PATH       = best_phishing_model.pkl
SCALER_PATH      = scaler.pkl

# Number of top SHAP features to include in XAI reasoning per prediction
TOP_SHAP_FEATURES = 3

# Loaded once at startup — not on every request — for maximum performance.

model    = None   # trained XGBClassifier
scaler   = None   # fitted StandardScaler
explainer = None  # shap.TreeExplainer (built once, reused per request)
feature_names = []   # ordered list of feature names the scalermodel expect


def load_artifacts()
    
    Load the trained XGBoost model and the fitted StandardScaler from disk.
    Both must be present in the Colab runtime directory.
    Initialises the SHAP TreeExplainer immediately after loading the model
    so it is warm and ready for every incoming request.
    
    global model, scaler, explainer, feature_names

    # ── Load model ─────────────────────────────────────────────────────────────
    if not os.path.exists(MODEL_PATH)
        raise FileNotFoundError(
            f[ERROR] '{MODEL_PATH}' not found. 
            Please upload it to the Colab runtime.
        )
    model = joblib.load(MODEL_PATH)
    print(f[OK] Model loaded  ← {MODEL_PATH})

    # ── Load scaler ────────────────────────────────────────────────────────────
    if not os.path.exists(SCALER_PATH)
        raise FileNotFoundError(
            f[ERROR] '{SCALER_PATH}' not found. 
            Please upload it to the Colab runtime.
        )
    scaler = joblib.load(SCALER_PATH)
    print(f[OK] Scaler loaded ← {SCALER_PATH})

    # ── Recover feature names ──────────────────────────────────────────────────
    # StandardScaler stores feature_names_in_ if it was fitted on a DataFrame.
    # This ensures the incoming JSON columns are aligned in the correct order.
    if hasattr(scaler, feature_names_in_)
        feature_names = list(scaler.feature_names_in_)
        print(f[OK] Feature names recovered from scaler ({len(feature_names)} features).)
    else
        # Fallback derive expected column count from scaler's mean_ array
        feature_names = [ffeature_{i} for i in range(len(scaler.mean_))]
        print(f[WARN] Scaler has no feature_names_in_ — using generic names. 
              fEnsure your JSON keys match the training column order exactly.)

    # ── Initialise SHAP TreeExplainer ──────────────────────────────────────────
    # Built once here (expensive) so every predict call is fast.
    # TreeExplainer is the correct explainer for XGBoost  tree-based models.
    print([INFO] Initialising SHAP TreeExplainer (one-time, ~5s)...)
    explainer = shap.TreeExplainer(model)
    print([OK] SHAP TreeExplainer ready.)


app = Flask(__name__)


# ── Health-check endpoint ──────────────────────────────────────────────────────
@app.route(, methods=[GET])
def health()
    
    Simple GET endpoint to confirm the API is live.
    Useful for smoke-testing the ngrok URL before sending real requests.
    
    return jsonify({
        status  online,
        service Phishing URL Detection API,
        version 1.0.0,
        endpoints {
            POST predict Send URL features as JSON to classify a URL.
        },
        timestamp datetime.utcnow().isoformat() + Z
    }), 200


# ── Main prediction endpoint ───────────────────────────────────────────────────
@app.route(predict, methods=[POST])
def predict()
    
    Accepts a JSON payload of URL features, scales them, runs XGBoost inference,
    computes SHAP values, and returns a structured JSON response with
      • prediction   (Safe or Phishing)
      • confidence   (probability %)
      • xai_reasoning (top-3 SHAP feature explanations in plain English)

    Example request body
    {
        URLLength 85,
        IsHTTPS 0,
        NoOfSubDomain 3,
        HasObfuscation 1,
        ...  (all training features)
    }
    
    # ── Guard ensure model is loaded ─────────────────────────────────────────
    if model is None or scaler is None or explainer is None
        return jsonify({
            status  error,
            message Model artifacts not loaded. Check server logs.
        }), 503

    # ── Parse JSON body ────────────────────────────────────────────────────────
    payload = request.get_json(silent=True)
    if payload is None
        return jsonify({
            status  error,
            message Request body must be valid JSON with Content-Type applicationjson.
        }), 400

    # ── Validate that all required features are present ───────────────────────
    missing = [f for f in feature_names if f not in payload]
    if missing
        return jsonify({
            status  error,
            message fMissing {len(missing)} required feature(s) {missing}
        }), 422

    # ── STEP 3 Build DataFrame and align column order ─────────────────────────
    # Converting to a DataFrame (not a bare array) preserves feature names,
    # which SHAP uses to label its output and which the scaler uses internally.
    # Columns are reordered to exactly match the order the scaler was fitted on.
    try
        input_df = pd.DataFrame([payload])[feature_names]
    except KeyError as e
        return jsonify({
            status  error,
            message fFeature alignment error {str(e)}
        }), 422

    # ── Apply StandardScaler (same object fitted during training) ──────────────
    # This converts raw feature values into the same z-score space the model
    # was trained on. Using a fresh scaler would produce wrong predictions.
    scaled_array = scaler.transform(input_df)
    scaled_df    = pd.DataFrame(scaled_array, columns=feature_names)

    # ── STEP 4A Model prediction ──────────────────────────────────────────────
    predicted_class = int(model.predict(scaled_df)[0])       # 0 = Safe, 1 = Phishing
    probabilities   = model.predict_proba(scaled_df)[0]      # [P(safe), P(phishing)]
    confidence      = round(float(probabilities[predicted_class])  100, 2)
    label           = Phishing if predicted_class == 1 else Safe

    # ── STEP 4B SHAP Local Explainability ────────────────────────────────────
    # shap_vals is a 1D array of shape (n_features,).
    # Each value = how much that feature pushed this prediction away from the
    # base rate. Positive → pushes toward Phishing. Negative → pushes toward Safe.
    raw_shap = explainer.shap_values(scaled_df, check_additivity=False)

    # For binary XGBoost, shap_values() returns either a 2D array (one row)
    # or a list with two matrices (one per class). Normalise to 1D.
    if isinstance(raw_shap, list)
        shap_vals = raw_shap[1][0]    # class-1 (Phishing) SHAP values
    else
        shap_vals = raw_shap[0]       # single-output shape (n_features,)

    # ── STEP 4C Extract Top-N SHAP features for XAI reasoning ────────────────
    # Sort by absolute magnitude so we surface the features with the
    # strongest influence regardless of direction (positive or negative).
    shap_series = pd.Series(shap_vals, index=feature_names)
    top_features = shap_series.abs().nlargest(TOP_SHAP_FEATURES)

    xai_reasoning = []
    for feat_name, abs_val in top_features.items()
        direction_val = shap_series[feat_name]        # signed value
        raw_value     = payload[feat_name]            # original (unscaled) input

        # Choose a human-readable risk phrase based on direction and prediction
        if direction_val  0
            if predicted_class == 1   # pushes toward Phishing in a Phishing result
                risk_phrase = significantly increased the phishing risk
            else                       # pushes toward Phishing but Safe won overall
                risk_phrase = was a suspicious signal (overridden by other features)
        else
            if predicted_class == 0   # pushes toward Safe in a Safe result
                risk_phrase = strongly indicated a legitimate URL
            else                       # pushes toward Safe but Phishing won overall
                risk_phrase = reduced risk slightly (not enough to override other signals)

        sentence = (
            fFeature '{feat_name}' (value {raw_value}) {risk_phrase} 
            f[SHAP impact {direction_val+.4f}].
        )
        xai_reasoning.append(sentence)

    # ── STEP 5 Build and return the JSON response ─────────────────────────────
    response = {
        status           success,
        prediction       label,
        predicted_class  predicted_class,
        confidence_score confidence,
        xai_reasoning    xai_reasoning,
        meta {
            model     XGBoost,
            explainer SHAP TreeExplainer,
            features_received len(payload),
            timestamp datetime.utcnow().isoformat() + Z
        }
    }

    return jsonify(response), 200


# ── Global error handlers ──────────────────────────────────────────────────────

@app.errorhandler(404)
def not_found(e)
    return jsonify({status error, message Endpoint not found.}), 404

@app.errorhandler(405)
def method_not_allowed(e)
    return jsonify({status error,
                    message Method not allowed. Use POST for predict.}), 405

@app.errorhandler(500)
def internal_error(e)
    return jsonify({status error,
                    message Internal server error. Check Colab logs.}), 500


def start_api()
    
    1. Authenticate ngrok with the provided token.
    2. Open a public HTTPS tunnel to local port 5000.
    3. Print the public URL so you can immediately test the API.
    4. Start the Flask development server (threaded=True allows concurrent requests).
    

    # ── Authenticate ngrok ─────────────────────────────────────────────────────
    if NGROK_AUTH_TOKEN == PASTE_YOUR_NGROK_AUTH_TOKEN_HERE
        raise ValueError(
            n[ERROR] You have not set your ngrok auth token.n
              1. Go to httpsdashboard.ngrok.comget-startedyour-authtokenn
              2. Copy your token and paste it into NGROK_AUTH_TOKEN above.n
        )

    conf.get_default().auth_token = NGROK_AUTH_TOKEN

    # Kill any previous ngrok tunnels to avoid 'ERR_NGROK_108' conflicts
    ngrok.kill()

    # Open a new HTTPS tunnel on port 5000
    tunnel     = ngrok.connect(PORT, http)
    public_url = tunnel.public_url

    # ── Print the public URL and test commands ─────────────────────────────────
    banner = f
╔══════════════════════════════════════════════════════════════════╗
║         🚀  Phishing URL Detection API is LIVE                   ║
╠══════════════════════════════════════════════════════════════════╣
║                                                                  ║
║  Public URL    {public_url48} ║
║  Local URL     http127.0.0.1{PORT}                           ║
║                                                                  ║
║  Endpoints                                                      ║
║    GET           → Health check                                 ║
║    POST predict  → Phishing URL classification + XAI            ║
║                                                                  ║
╠══════════════════════════════════════════════════════════════════╣
║  Test with curl (paste in your terminal or Postman)             ║
║                                                                  ║
║  curl -X POST {public_url}predict           ║
║    -H Content-Type applicationjson                          ║
║    -d '{{URLLength120,IsHTTPS0,NoOfSubDomain4}}'        ║
║                                                                  ║
╚══════════════════════════════════════════════════════════════════╝

    print(banner)

    # ── Start Flask ────────────────────────────────────────────────────────────
    # use_reloader=False  → prevents Colab double-start bug
    # threaded=True       → handles multiple simultaneous requests
    app.run(host=0.0.0.0, port=PORT, use_reloader=False, threaded=True)


# Load model artifacts first — if either file is missing, we stop here
# with a clear error rather than crashing silently on the first request.
print(=  66)
print(  Phishing URL Detection API — Initialising)
print(=  66)

try
    load_artifacts()
except FileNotFoundError as e
    print(str(e))
    print(n[STOP] Upload both .pkl files to Colab, then re-run this cell.)
else
    # All artifacts loaded — start the API in a background thread so Colab
    # doesn't hang and you can still run other cells while the server is live.
    api_thread = threading.Thread(target=start_api, daemon=True)
    api_thread.start()

# Phishing URL Detection System
# Task 14 Visualization — 3 Standalone Graphs
#
# Generates
#   Graph 2 — Grouped Metrics Comparison Chart (AccuracyPrecisionRecallF1)
#
# Runs 100% standalone using the mock data defined below.
# To use real data replace the values in METRICS and CONF_MATRIX.

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import matplotlib.patches as mpatches
import seaborn as sns

# Replace these with your actual evaluation results when running for real.

# Dictionary of per-model metrics (all values between 0 and 1)
METRICS = {
    LogisticnRegression {
        Accuracy 0.9421, Precision 0.9425, Recall 0.9418, F1-Score 0.9420
    },
    KNN {
        Accuracy 0.9683, Precision 0.9687, Recall 0.9680, F1-Score 0.9683
    },
    SVM {
        Accuracy 0.9754, Precision 0.9756, Recall 0.9751, F1-Score 0.9753
    },
    ANNn(MLP) {
        Accuracy 0.9812, Precision 0.9814, Recall 0.9810, F1-Score 0.9812
    },
    RandomnForest {
        Accuracy 0.9891, Precision 0.9893, Recall 0.9889, F1-Score 0.9891
    },
    XGBoost {
        Accuracy 0.9934, Precision 0.9936, Recall 0.9932, F1-Score 0.9934
    },
}

# Confusion matrix for the best model (XGBoost)
# Layout [[TN, FP], [FN, TP]]  — rows = true labels, cols = predicted labels
CONF_MATRIX = np.array([
    [20143,   46],   # True Safe   → predicted Safe (TN)  predicted Phishing (FP)
    [   77, 26893],  # True Phishing → predicted Safe (FN)  predicted Phishing (TP)
])

# Name of the best model (used to colour-highlight its bar in Graph 1)
BEST_MODEL = XGBoost

# One rcParams block keeps all three graphs visually consistent.

plt.rcParams.update({
    figure.facecolor  #0F1117,
    axes.facecolor    #181C27,
    axes.edgecolor    #2A2F45,
    axes.labelcolor   #C8D0E7,
    axes.titlecolor   #FFFFFF,
    axes.titlesize    14,
    axes.titleweight  bold,
    axes.labelsize    11,
    axes.grid         True,
    grid.color        #2A2F45,
    grid.linestyle    --,
    grid.alpha        0.5,
    xtick.color       #8892B0,
    ytick.color       #8892B0,
    xtick.labelsize   9,
    ytick.labelsize   9,
    text.color        #C8D0E7,
    legend.facecolor  #1E2235,
    legend.edgecolor  #2A2F45,
    legend.fontsize   9.5,
    font.family       DejaVu Sans,
})

# Colour palette
CLR_BEST    = #00C48C   # vivid teal-green  → best model (XGBoost)
CLR_DEFAULT = #5C6BC0   # muted indigo       → all other models
CLR_WINNER_STAR = #FFD700  # gold            → star annotation

# Four colours for the grouped metrics chart (one per metric)
METRIC_COLOURS = {
    Accuracy  #5C6BC0,   # indigo
    Precision #00C48C,   # teal
    Recall    #FF7043,   # deep orange
    F1-Score  #AB47BC,   # purple
}

METRIC_KEYS = [Accuracy, Precision, Recall, F1-Score]

# Small helper to add a branded footer to any figure
def _footer(fig)
    fig.text(0.99, 0.01,
             PhiUSIIL Phishing URL Detection System  ·  Task 14 Visualization,
             ha=right, va=bottom,
             fontsize=7.5, color=#3D4566, style=italic)


# Shows each model's accuracy sorted highest → lowest.
# The best model's bar is highlighted in teal-green.

print(─  55)
print(Generating Graph 1 AccuracyPerformance Bar Chart...)
print(─  55)

# Build a simple list of (model_name, accuracy) sorted descending
sorted_models = sorted(
    METRICS.items(),
    key=lambda item item[1][Accuracy],
    reverse=True
)
model_labels = [m[0] for m in sorted_models]
accuracies   = [m[1][Accuracy]  100 for m in sorted_models]   # convert to %

# Assign bar colours teal for best model, indigo for everyone else
bar_colours = [CLR_BEST if label == BEST_MODEL else CLR_DEFAULT
               for label in model_labels]

fig1, ax1 = plt.subplots(figsize=(12, 6))
fig1.patch.set_facecolor(#0F1117)

bars = ax1.bar(
    model_labels, accuracies,
    color=bar_colours,
    edgecolor=#0F1117,
    linewidth=1.0,
    width=0.55,
    zorder=3
)

# ── Data labels percentage on top of each bar ────────────────────────────────
for bar, colour in zip(bars, bar_colours)
    height = bar.get_height()
    ax1.text(
        bar.get_x() + bar.get_width()  2,
        height + 0.04,               # tiny gap above the bar top
        f{height.2f}%,
        ha=center, va=bottom,
        fontsize=10, fontweight=bold,
        color=colour
    )

# ── Gold star above the winning bar ──────────────────────────────────────────
best_idx = model_labels.index(BEST_MODEL)
best_bar = bars[best_idx]
ax1.text(
    best_bar.get_x() + best_bar.get_width()  2,
    best_bar.get_height() + 0.55,
    ★  Best Model,
    ha=center, va=bottom,
    fontsize=10, fontweight=bold, color=CLR_WINNER_STAR
)

# ── Thin dashed reference line at the best accuracy ──────────────────────────
ax1.axhline(
    max(accuracies),
    color=CLR_BEST, linewidth=0.9, linestyle=--, alpha=0.35, zorder=2
)

# ── Axes formatting ───────────────────────────────────────────────────────────
y_lo = max(0, min(accuracies) - 2.0)
y_hi = min(100, max(accuracies) + 2.0)
ax1.set_ylim(y_lo, y_hi)
ax1.yaxis.set_major_formatter(mticker.FormatStrFormatter(%.1f%%))
ax1.set_title(Model Accuracy Comparison  ·  Sorted Highest → Lowest, pad=16)
ax1.set_ylabel(Accuracy (%), labelpad=10)
ax1.set_xlabel(Classifier, labelpad=10)
ax1.spines[[top, right]].set_visible(False)
ax1.tick_params(axis=x, labelsize=9)

# Legend
legend_handles = [
    mpatches.Patch(color=CLR_BEST,    label=fBest Model ({BEST_MODEL})),
    mpatches.Patch(color=CLR_DEFAULT, label=Other Models),
]
ax1.legend(handles=legend_handles, loc=lower right, framealpha=0.9)

_footer(fig1)
plt.tight_layout()
plt.show()
print([DONE] Graph 1 rendered.n)


# Displays Accuracy, Precision, Recall, and F1-Score side-by-side
# for all 6 classifiers so the instructor can compare them at a glance.

print(─  55)
print(Generating Graph 2 Grouped Model Comparison Chart...)
print(─  55)

# Use the same sorted order as Graph 1 for visual consistency
n_models  = len(sorted_models)
n_metrics = len(METRIC_KEYS)

# Bar positions for each model we place n_metrics bars side-by-side
x         = np.arange(n_models)          # centre position of each model group
bar_width = 0.18                          # width of each individual metric bar
offsets   = np.linspace(
    -(n_metrics - 1)  2  bar_width,
    (n_metrics - 1)  2  bar_width,
    n_metrics
)

fig2, ax2 = plt.subplots(figsize=(15, 7))
fig2.patch.set_facecolor(#0F1117)

for i, (metric, offset) in enumerate(zip(METRIC_KEYS, offsets))
    values = [METRICS[m][metric] for m in model_labels]

    bars2 = ax2.bar(
        x + offset, values,
        width=bar_width,
        color=METRIC_COLOURS[metric],
        edgecolor=#0F1117,
        linewidth=0.7,
        label=metric,
        alpha=0.88,
        zorder=3
    )

    for bar in bars2
        h = bar.get_height()
        ax2.text(
            bar.get_x() + bar.get_width()  2,
            h + 0.0008,
            f{h.2f},
            ha=center, va=bottom,
            fontsize=7.2, fontweight=bold,
            color=METRIC_COLOURS[metric]
        )

# ── Highlight the best model group with a subtle background band ──────────────
best_x = x[best_idx]
ax2.axvspan(best_x - 0.44, best_x + 0.44,
            alpha=0.07, color=CLR_BEST, zorder=0)
ax2.text(
    best_x, ax2.get_ylim()[1] if ax2.get_ylim()[1]  0 else 1.005,
    ★  Best,
    ha=center, va=bottom,
    fontsize=9.5, fontweight=bold, color=CLR_WINNER_STAR
)

# ── Axes formatting ───────────────────────────────────────────────────────────
ax2.set_xticks(x)
ax2.set_xticklabels(model_labels, fontsize=9)
ax2.set_ylim(min(
    METRICS[m][k] for m in METRICS for k in METRIC_KEYS) - 0.015, 1.015)
ax2.yaxis.set_major_formatter(mticker.FormatStrFormatter(%.2f))
ax2.set_title(Detailed Model Comparison  ·  Accuracy · Precision · Recall · F1-Score, pad=16)
ax2.set_ylabel(Score  (0 – 1), labelpad=10)
ax2.set_xlabel(Classifier, labelpad=10)
ax2.spines[[top, right]].set_visible(False)
ax2.legend(title=Metric, title_fontsize=9.5,
           loc=lower right, framealpha=0.9, ncol=2)

_footer(fig2)
plt.tight_layout()
plt.show()
print([DONE] Graph 2 rendered.n)


# Visualises TN  FP  FN  TP for the best model on the test set.
# Rows = True label, Columns = Predicted label.

print(─  55)
print(Generating Graph 3 XGBoost Confusion Matrix Heatmap...)
print(─  55)

# Compute per-cell percentage of the total test set for richer annotations
total         = CONF_MATRIX.sum()
pct_matrix    = CONF_MATRIX  total  100

# Build annotation strings count + percentage on two lines
annot_labels  = np.array([
    [f{count,}n({pct.2f}%)
     for count, pct in zip(row_c, row_p)]
    for row_c, row_p in zip(CONF_MATRIX, pct_matrix)
])

# Friendly cell labels (placed in each quadrant corner for clarity)
cell_names = np.array([
    [True Negativen(TN), False Positiven(FP)],
    [False Negativen(FN), True Positiven(TP)],
])

fig3, ax3 = plt.subplots(figsize=(8, 7))
fig3.patch.set_facecolor(#0F1117)
ax3.set_facecolor(#181C27)

# Draw the heatmap — YlOrRd goes light (low) → dark-red (high)
hm = sns.heatmap(
    CONF_MATRIX,
    ax=ax3,
    cmap=YlOrRd,
    annot=annot_labels,
    fmt=,
    annot_kws={size 14, weight bold, color #1A1A2E},
    linewidths=2.5,
    linecolor=#0F1117,
    xticklabels=[Predicted Safe (0), Predicted Phishing (1)],
    yticklabels=[Actual Safe (0), Actual Phishing (1)],
    cbar_kws={shrink 0.78, label Sample Count},
    square=True
)

hm.collections[0].colorbar.ax.tick_params(colors=#8892B0, labelsize=8)
hm.collections[0].colorbar.set_label(Sample Count, color=#8892B0, fontsize=9)

# ── White border on the diagonal (correct predictions) ───────────────────────
for i in range(2)
    ax3.add_patch(plt.Rectangle(
        (i, i), 1, 1,
        fill=False, edgecolor=white, linewidth=3.0
    ))

# ── Quadrant labels (TN  FP  FN  TP) in upper-left corner of each cell ───
for row in range(2)
    for col in range(2)
        ax3.text(
            col + 0.04, row + 0.10,
            cell_names[row, col],
            ha=left, va=top,
            fontsize=7.5, color=#666E8A, style=italic
        )

# ── Summary statistics below the chart ───────────────────────────────────────
tn, fp, fn, tp = CONF_MATRIX.ravel()
accuracy  = (tp + tn)  total  100
precision = tp  (tp + fp)  100
recall    = tp  (tp + fn)  100
f1        = 2  precision  recall  (precision + recall)

stats_text = (
    fAccuracy {accuracy.2f}%      
    fPrecision {precision.2f}%      
    fRecall {recall.2f}%      
    fF1-Score {f1.2f}%
)
fig3.text(
    0.5, -0.02, stats_text,
    ha=center, va=top,
    fontsize=9.5, color=#C8D0E7,
    bbox=dict(boxstyle=round,pad=0.5, fc=#1E2235, ec=#2A2F45, alpha=0.9)
)

# ── Axes formatting ───────────────────────────────────────────────────────────
ax3.set_title(
    fConfusion Matrix  ·  XGBoost (Best Model)n
    fTest Set {total,} samples,
    fontsize=14, pad=14
)
ax3.set_xlabel(Predicted Label, labelpad=12, fontsize=11)
ax3.set_ylabel(True Label,      labelpad=12, fontsize=11)
ax3.tick_params(axis=x, rotation=0,  labelsize=9.5)
ax3.tick_params(axis=y, rotation=0,  labelsize=9.5)

_footer(fig3)
plt.tight_layout()
plt.show()
print([DONE] Graph 3 rendered.n)

print(=  55)
print(All 3 visualizations generated successfully.)
print(=  55)